// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcUY9rf7M_iikUHBCcAhkST2DtBcQBNw',
    appId: '1:782722853675:android:07392a9322d276cac7336e',
    messagingSenderId: '782722853675',
    projectId: 'trifecta-laggedskapari',
    storageBucket: 'trifecta-laggedskapari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPYkN68ZB_aC4hf17gNHbV0z00U6irlg',
    appId: '1:782722853675:ios:6d053cdb729ea093c7336e',
    messagingSenderId: '782722853675',
    projectId: 'trifecta-laggedskapari',
    storageBucket: 'trifecta-laggedskapari.appspot.com',
    iosBundleId: 'com.laggedskapari.trifecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPYkN68ZB_aC4hf17gNHbV0z00U6irlg',
    appId: '1:782722853675:ios:6d053cdb729ea093c7336e',
    messagingSenderId: '782722853675',
    projectId: 'trifecta-laggedskapari',
    storageBucket: 'trifecta-laggedskapari.appspot.com',
    iosBundleId: 'com.laggedskapari.trifecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6VnvbviBu5vdtmvycDYFvbq_oy6rAyAs',
    appId: '1:782722853675:web:5fc70f20e8f0f631c7336e',
    messagingSenderId: '782722853675',
    projectId: 'trifecta-laggedskapari',
    authDomain: 'trifecta-laggedskapari.firebaseapp.com',
    storageBucket: 'trifecta-laggedskapari.appspot.com',
    measurementId: 'G-XG1G2H73TR',
  );

}